# r=open("D:\pythonprograms\exception_handling\write and read and append\demo1",'w')
# r.write("herooo")
# r.write("heroo1../n")
# r.close()
# print("done")
# r=open("D:\pythonprograms\exception_handling\write and read and append\demo1",'r')
# print(r.read())
# r=open("D:\pythonprograms\exception_handling\write and read and append\demo1",'a')
# r.write("/n")
# r.write("ggyjhj")
# r.close()
# r=open("D:\pythonprograms\exception_handling\write and read and append\demo1",'r')
# print(r.read())
# r.close()
# r=open("C:\Users\admin\OneDrive\Desktop" ,'w')
# r.write("yetfhwgkj")
# r.close()
